# Generated by Django 4.1 on 2022-09-13 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Portfolio",),
        migrations.RemoveField(model_name="userprofile", name="skills",),
        migrations.DeleteModel(name="Skill",),
    ]
