# Generated by Django 4.1 on 2022-09-22 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_delete_portfolio_remove_userprofile_skills_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="Certificate",),
        migrations.RemoveField(model_name="userprofile", name="cv",),
    ]
