# Generated by Django 4.1 on 2022-09-27 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_delete_certificate_remove_userprofile_cv"),
    ]

    operations = [
        migrations.RemoveField(model_name="testimonial", name="role",),
    ]
